name: benpaddock.net CI

on:
    push:
        branches: ["master"]
    pull_request:
        branches: ["master"]

jobs:
    test:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [22.x]

        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "npm"
            - uses: browser-actions/setup-chrome@v1
              with:
                  chrome-version: latest
                  install-chromedriver: true
            - name: Install Vercel CLI
              run: npm install --global vercel@latest
            - name: Link Vercel project to repo
              run: vercel link --yes --token=${{ secrets.VERCEL_TOKEN }}
            - name: Pull Vercel environment variables
              run: vercel env pull --token=${{ secrets.VERCEL_TOKEN }}
            - run: npm ci
            - run: npm run build
            - run: npm run a11y
            - run: npm test
